// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.27.0
// source: createtestrun.proto

package createtestrun

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTestRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestRun       *TestRun               `protobuf:"bytes,1,opt,name=test_run,json=testRun,proto3" json:"test_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTestRunRequest) Reset() {
	*x = CreateTestRunRequest{}
	mi := &file_createtestrun_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTestRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTestRunRequest) ProtoMessage() {}

func (x *CreateTestRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_createtestrun_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTestRunRequest.ProtoReflect.Descriptor instead.
func (*CreateTestRunRequest) Descriptor() ([]byte, []int) {
	return file_createtestrun_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTestRunRequest) GetTestRun() *TestRun {
	if x != nil {
		return x.TestRun
	}
	return nil
}

type CreateTestRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TestRun       *TestRun               `protobuf:"bytes,3,opt,name=test_run,json=testRun,proto3" json:"test_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTestRunResponse) Reset() {
	*x = CreateTestRunResponse{}
	mi := &file_createtestrun_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTestRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTestRunResponse) ProtoMessage() {}

func (x *CreateTestRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_createtestrun_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTestRunResponse.ProtoReflect.Descriptor instead.
func (*CreateTestRunResponse) Descriptor() ([]byte, []int) {
	return file_createtestrun_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTestRunResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTestRunResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CreateTestRunResponse) GetTestRun() *TestRun {
	if x != nil {
		return x.TestRun
	}
	return nil
}

type TestRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SuiteRuns     []*SuiteRun            `protobuf:"bytes,3,rep,name=suite_runs,json=suiteRuns,proto3" json:"suite_runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRun) Reset() {
	*x = TestRun{}
	mi := &file_createtestrun_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRun) ProtoMessage() {}

func (x *TestRun) ProtoReflect() protoreflect.Message {
	mi := &file_createtestrun_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRun.ProtoReflect.Descriptor instead.
func (*TestRun) Descriptor() ([]byte, []int) {
	return file_createtestrun_proto_rawDescGZIP(), []int{2}
}

func (x *TestRun) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TestRun) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestRun) GetSuiteRuns() []*SuiteRun {
	if x != nil {
		return x.SuiteRuns
	}
	return nil
}

type SuiteRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecRuns      []*SpecRun             `protobuf:"bytes,1,rep,name=spec_runs,json=specRuns,proto3" json:"spec_runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuiteRun) Reset() {
	*x = SuiteRun{}
	mi := &file_createtestrun_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuiteRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuiteRun) ProtoMessage() {}

func (x *SuiteRun) ProtoReflect() protoreflect.Message {
	mi := &file_createtestrun_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuiteRun.ProtoReflect.Descriptor instead.
func (*SuiteRun) Descriptor() ([]byte, []int) {
	return file_createtestrun_proto_rawDescGZIP(), []int{3}
}

func (x *SuiteRun) GetSpecRuns() []*SpecRun {
	if x != nil {
		return x.SpecRuns
	}
	return nil
}

type SpecRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecRun) Reset() {
	*x = SpecRun{}
	mi := &file_createtestrun_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecRun) ProtoMessage() {}

func (x *SpecRun) ProtoReflect() protoreflect.Message {
	mi := &file_createtestrun_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecRun.ProtoReflect.Descriptor instead.
func (*SpecRun) Descriptor() ([]byte, []int) {
	return file_createtestrun_proto_rawDescGZIP(), []int{4}
}

func (x *SpecRun) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_createtestrun_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_createtestrun_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_createtestrun_proto_rawDescGZIP(), []int{5}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_createtestrun_proto protoreflect.FileDescriptor

var file_createtestrun_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x65, 0x73,
	0x74, 0x72, 0x75, 0x6e, 0x22, 0x49, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65,
	0x73, 0x74, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x08,
	0x74, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x75, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x2e, 0x54,
	0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x52, 0x07, 0x74, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x22,
	0x89, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x74, 0x65, 0x73, 0x74,
	0x5f, 0x72, 0x75, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52,
	0x75, 0x6e, 0x52, 0x07, 0x74, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x22, 0x65, 0x0a, 0x07, 0x54,
	0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x73, 0x75,
	0x69, 0x74, 0x65, 0x5f, 0x72, 0x75, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x2e, 0x53,
	0x75, 0x69, 0x74, 0x65, 0x52, 0x75, 0x6e, 0x52, 0x09, 0x73, 0x75, 0x69, 0x74, 0x65, 0x52, 0x75,
	0x6e, 0x73, 0x22, 0x3f, 0x0a, 0x08, 0x53, 0x75, 0x69, 0x74, 0x65, 0x52, 0x75, 0x6e, 0x12, 0x33,
	0x0a, 0x09, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x72, 0x75, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75,
	0x6e, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x52, 0x75, 0x6e, 0x52, 0x08, 0x73, 0x70, 0x65, 0x63, 0x52,
	0x75, 0x6e, 0x73, 0x22, 0x31, 0x0a, 0x07, 0x53, 0x70, 0x65, 0x63, 0x52, 0x75, 0x6e, 0x12, 0x26,
	0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x2e, 0x54, 0x61, 0x67,
	0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x19, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x32, 0x6c, 0x0a, 0x0e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x73,
	0x74, 0x52, 0x75, 0x6e, 0x12, 0x23, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x65, 0x73,
	0x74, 0x72, 0x75, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x73, 0x74, 0x52,
	0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x3b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x65, 0x73, 0x74,
	0x72, 0x75, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_createtestrun_proto_rawDescOnce sync.Once
	file_createtestrun_proto_rawDescData = file_createtestrun_proto_rawDesc
)

func file_createtestrun_proto_rawDescGZIP() []byte {
	file_createtestrun_proto_rawDescOnce.Do(func() {
		file_createtestrun_proto_rawDescData = protoimpl.X.CompressGZIP(file_createtestrun_proto_rawDescData)
	})
	return file_createtestrun_proto_rawDescData
}

var file_createtestrun_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_createtestrun_proto_goTypes = []any{
	(*CreateTestRunRequest)(nil),  // 0: createtestrun.CreateTestRunRequest
	(*CreateTestRunResponse)(nil), // 1: createtestrun.CreateTestRunResponse
	(*TestRun)(nil),               // 2: createtestrun.TestRun
	(*SuiteRun)(nil),              // 3: createtestrun.SuiteRun
	(*SpecRun)(nil),               // 4: createtestrun.SpecRun
	(*Tag)(nil),                   // 5: createtestrun.Tag
}
var file_createtestrun_proto_depIdxs = []int32{
	2, // 0: createtestrun.CreateTestRunRequest.test_run:type_name -> createtestrun.TestRun
	2, // 1: createtestrun.CreateTestRunResponse.test_run:type_name -> createtestrun.TestRun
	3, // 2: createtestrun.TestRun.suite_runs:type_name -> createtestrun.SuiteRun
	4, // 3: createtestrun.SuiteRun.spec_runs:type_name -> createtestrun.SpecRun
	5, // 4: createtestrun.SpecRun.tags:type_name -> createtestrun.Tag
	0, // 5: createtestrun.TestRunService.CreateTestRun:input_type -> createtestrun.CreateTestRunRequest
	1, // 6: createtestrun.TestRunService.CreateTestRun:output_type -> createtestrun.CreateTestRunResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_createtestrun_proto_init() }
func file_createtestrun_proto_init() {
	if File_createtestrun_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_createtestrun_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_createtestrun_proto_goTypes,
		DependencyIndexes: file_createtestrun_proto_depIdxs,
		MessageInfos:      file_createtestrun_proto_msgTypes,
	}.Build()
	File_createtestrun_proto = out.File
	file_createtestrun_proto_rawDesc = nil
	file_createtestrun_proto_goTypes = nil
	file_createtestrun_proto_depIdxs = nil
}
