// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	jwk "github.com/lestrrat-go/jwx/v2/jwk"
	mock "github.com/stretchr/testify/mock"
)

// JWKSFetcher is an autogenerated mock type for the JWKSFetcher type
type JWKSFetcher struct {
	mock.Mock
}

// FetchKeys provides a mock function with given fields: ctx, jwksUrl
func (_m *JWKSFetcher) FetchKeys(ctx context.Context, jwksUrl string) (jwk.Set, error) {
	ret := _m.Called(ctx, jwksUrl)

	if len(ret) == 0 {
		panic("no return value specified for FetchKeys")
	}

	var r0 jwk.Set
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (jwk.Set, error)); ok {
		return rf(ctx, jwksUrl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) jwk.Set); ok {
		r0 = rf(ctx, jwksUrl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwk.Set)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jwksUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, jwksUrl
func (_m *JWKSFetcher) Get(ctx context.Context, jwksUrl string) (jwk.Set, error) {
	ret := _m.Called(ctx, jwksUrl)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 jwk.Set
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (jwk.Set, error)); ok {
		return rf(ctx, jwksUrl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) jwk.Set); ok {
		r0 = rf(ctx, jwksUrl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwk.Set)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jwksUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Refresh provides a mock function with given fields: ctx, jwksUrl
func (_m *JWKSFetcher) Refresh(ctx context.Context, jwksUrl string) (jwk.Set, error) {
	ret := _m.Called(ctx, jwksUrl)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 jwk.Set
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (jwk.Set, error)); ok {
		return rf(ctx, jwksUrl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) jwk.Set); ok {
		r0 = rf(ctx, jwksUrl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwk.Set)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jwksUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: jwksUrl, options
func (_m *JWKSFetcher) Register(jwksUrl string, options ...jwk.RegisterOption) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, jwksUrl)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ...jwk.RegisterOption) error); ok {
		r0 = rf(jwksUrl, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewJWKSFetcher creates a new instance of JWKSFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWKSFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWKSFetcher {
	mock := &JWKSFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
