// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.0
// source: gettestrunbyid.proto

package gettestrunbyid

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestRunServiceClient is the client API for TestRunService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestRunServiceClient interface {
	GetTestRunByID(ctx context.Context, in *GetTestRunByIDRequest, opts ...grpc.CallOption) (*GetTestRunByIDResponse, error)
}

type testRunServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestRunServiceClient(cc grpc.ClientConnInterface) TestRunServiceClient {
	return &testRunServiceClient{cc}
}

func (c *testRunServiceClient) GetTestRunByID(ctx context.Context, in *GetTestRunByIDRequest, opts ...grpc.CallOption) (*GetTestRunByIDResponse, error) {
	out := new(GetTestRunByIDResponse)
	err := c.cc.Invoke(ctx, "/mypackage.TestRunService/GetTestRunByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestRunServiceServer is the server API for TestRunService service.
// All implementations must embed UnimplementedTestRunServiceServer
// for forward compatibility
type TestRunServiceServer interface {
	GetTestRunByID(context.Context, *GetTestRunByIDRequest) (*GetTestRunByIDResponse, error)
	mustEmbedUnimplementedTestRunServiceServer()
}

// UnimplementedTestRunServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTestRunServiceServer struct {
}

func (UnimplementedTestRunServiceServer) GetTestRunByID(context.Context, *GetTestRunByIDRequest) (*GetTestRunByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTestRunByID not implemented")
}
func (UnimplementedTestRunServiceServer) mustEmbedUnimplementedTestRunServiceServer() {}

// UnsafeTestRunServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestRunServiceServer will
// result in compilation errors.
type UnsafeTestRunServiceServer interface {
	mustEmbedUnimplementedTestRunServiceServer()
}

func RegisterTestRunServiceServer(s grpc.ServiceRegistrar, srv TestRunServiceServer) {
	s.RegisterService(&TestRunService_ServiceDesc, srv)
}

func _TestRunService_GetTestRunByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTestRunByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestRunServiceServer).GetTestRunByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mypackage.TestRunService/GetTestRunByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestRunServiceServer).GetTestRunByID(ctx, req.(*GetTestRunByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TestRunService_ServiceDesc is the grpc.ServiceDesc for TestRunService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestRunService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mypackage.TestRunService",
	HandlerType: (*TestRunServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTestRunByID",
			Handler:    _TestRunService_GetTestRunByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gettestrunbyid.proto",
}
