// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.27.0
// source: reporttestrunall.proto

package reporttestrunall

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request and Response messages
type ReportTestRunAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTestRunAllRequest) Reset() {
	*x = ReportTestRunAllRequest{}
	mi := &file_reporttestrunall_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTestRunAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTestRunAllRequest) ProtoMessage() {}

func (x *ReportTestRunAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reporttestrunall_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTestRunAllRequest.ProtoReflect.Descriptor instead.
func (*ReportTestRunAllRequest) Descriptor() ([]byte, []int) {
	return file_reporttestrunall_proto_rawDescGZIP(), []int{0}
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_reporttestrunall_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_reporttestrunall_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_reporttestrunall_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SpecRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecRun) Reset() {
	*x = SpecRun{}
	mi := &file_reporttestrunall_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecRun) ProtoMessage() {}

func (x *SpecRun) ProtoReflect() protoreflect.Message {
	mi := &file_reporttestrunall_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecRun.ProtoReflect.Descriptor instead.
func (*SpecRun) Descriptor() ([]byte, []int) {
	return file_reporttestrunall_proto_rawDescGZIP(), []int{2}
}

func (x *SpecRun) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SuiteRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecRuns      []*SpecRun             `protobuf:"bytes,1,rep,name=specRuns,proto3" json:"specRuns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuiteRun) Reset() {
	*x = SuiteRun{}
	mi := &file_reporttestrunall_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuiteRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuiteRun) ProtoMessage() {}

func (x *SuiteRun) ProtoReflect() protoreflect.Message {
	mi := &file_reporttestrunall_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuiteRun.ProtoReflect.Descriptor instead.
func (*SuiteRun) Descriptor() ([]byte, []int) {
	return file_reporttestrunall_proto_rawDescGZIP(), []int{3}
}

func (x *SuiteRun) GetSpecRuns() []*SpecRun {
	if x != nil {
		return x.SpecRuns
	}
	return nil
}

type TestRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SuiteRuns     []*SuiteRun            `protobuf:"bytes,2,rep,name=suiteRuns,proto3" json:"suiteRuns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRun) Reset() {
	*x = TestRun{}
	mi := &file_reporttestrunall_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRun) ProtoMessage() {}

func (x *TestRun) ProtoReflect() protoreflect.Message {
	mi := &file_reporttestrunall_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRun.ProtoReflect.Descriptor instead.
func (*TestRun) Descriptor() ([]byte, []int) {
	return file_reporttestrunall_proto_rawDescGZIP(), []int{4}
}

func (x *TestRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestRun) GetSuiteRuns() []*SuiteRun {
	if x != nil {
		return x.SuiteRuns
	}
	return nil
}

type ReportTestRunAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportHeader  string                 `protobuf:"bytes,1,opt,name=reportHeader,proto3" json:"reportHeader,omitempty"`
	TestRuns      []*TestRun             `protobuf:"bytes,2,rep,name=testRuns,proto3" json:"testRuns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTestRunAllResponse) Reset() {
	*x = ReportTestRunAllResponse{}
	mi := &file_reporttestrunall_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTestRunAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTestRunAllResponse) ProtoMessage() {}

func (x *ReportTestRunAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reporttestrunall_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTestRunAllResponse.ProtoReflect.Descriptor instead.
func (*ReportTestRunAllResponse) Descriptor() ([]byte, []int) {
	return file_reporttestrunall_proto_rawDescGZIP(), []int{5}
}

func (x *ReportTestRunAllResponse) GetReportHeader() string {
	if x != nil {
		return x.ReportHeader
	}
	return ""
}

func (x *ReportTestRunAllResponse) GetTestRuns() []*TestRun {
	if x != nil {
		return x.TestRuns
	}
	return nil
}

var File_reporttestrunall_proto protoreflect.FileDescriptor

var file_reporttestrunall_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x61,
	0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x61, 0x6c, 0x6c, 0x22, 0x19, 0x0a, 0x17, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x34, 0x0a, 0x07, 0x53, 0x70, 0x65, 0x63, 0x52, 0x75, 0x6e, 0x12, 0x29, 0x0a, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x61, 0x6c, 0x6c, 0x2e, 0x54, 0x61, 0x67,
	0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x41, 0x0a, 0x08, 0x53, 0x75, 0x69, 0x74, 0x65, 0x52,
	0x75, 0x6e, 0x12, 0x35, 0x0a, 0x08, 0x73, 0x70, 0x65, 0x63, 0x52, 0x75, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x74, 0x65, 0x73,
	0x74, 0x72, 0x75, 0x6e, 0x61, 0x6c, 0x6c, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x52, 0x75, 0x6e, 0x52,
	0x08, 0x73, 0x70, 0x65, 0x63, 0x52, 0x75, 0x6e, 0x73, 0x22, 0x53, 0x0a, 0x07, 0x54, 0x65, 0x73,
	0x74, 0x52, 0x75, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x73, 0x75, 0x69, 0x74, 0x65, 0x52, 0x75, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x61, 0x6c, 0x6c, 0x2e, 0x53, 0x75, 0x69, 0x74, 0x65,
	0x52, 0x75, 0x6e, 0x52, 0x09, 0x73, 0x75, 0x69, 0x74, 0x65, 0x52, 0x75, 0x6e, 0x73, 0x22, 0x75,
	0x0a, 0x18, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x35,
	0x0a, 0x08, 0x74, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e,
	0x61, 0x6c, 0x6c, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x52, 0x08, 0x74, 0x65, 0x73,
	0x74, 0x52, 0x75, 0x6e, 0x73, 0x32, 0x7b, 0x0a, 0x0e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x69, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x41, 0x6c, 0x6c, 0x12, 0x29, 0x2e, 0x72, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x61, 0x6c, 0x6c, 0x2e, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x74,
	0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x61, 0x6c, 0x6c, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x3b, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x74,
	0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x61, 0x6c, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_reporttestrunall_proto_rawDescOnce sync.Once
	file_reporttestrunall_proto_rawDescData = file_reporttestrunall_proto_rawDesc
)

func file_reporttestrunall_proto_rawDescGZIP() []byte {
	file_reporttestrunall_proto_rawDescOnce.Do(func() {
		file_reporttestrunall_proto_rawDescData = protoimpl.X.CompressGZIP(file_reporttestrunall_proto_rawDescData)
	})
	return file_reporttestrunall_proto_rawDescData
}

var file_reporttestrunall_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_reporttestrunall_proto_goTypes = []any{
	(*ReportTestRunAllRequest)(nil),  // 0: reporttestrunall.ReportTestRunAllRequest
	(*Tag)(nil),                      // 1: reporttestrunall.Tag
	(*SpecRun)(nil),                  // 2: reporttestrunall.SpecRun
	(*SuiteRun)(nil),                 // 3: reporttestrunall.SuiteRun
	(*TestRun)(nil),                  // 4: reporttestrunall.TestRun
	(*ReportTestRunAllResponse)(nil), // 5: reporttestrunall.ReportTestRunAllResponse
}
var file_reporttestrunall_proto_depIdxs = []int32{
	1, // 0: reporttestrunall.SpecRun.tags:type_name -> reporttestrunall.Tag
	2, // 1: reporttestrunall.SuiteRun.specRuns:type_name -> reporttestrunall.SpecRun
	3, // 2: reporttestrunall.TestRun.suiteRuns:type_name -> reporttestrunall.SuiteRun
	4, // 3: reporttestrunall.ReportTestRunAllResponse.testRuns:type_name -> reporttestrunall.TestRun
	0, // 4: reporttestrunall.TestRunService.ReportTestRunAll:input_type -> reporttestrunall.ReportTestRunAllRequest
	5, // 5: reporttestrunall.TestRunService.ReportTestRunAll:output_type -> reporttestrunall.ReportTestRunAllResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_reporttestrunall_proto_init() }
func file_reporttestrunall_proto_init() {
	if File_reporttestrunall_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reporttestrunall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reporttestrunall_proto_goTypes,
		DependencyIndexes: file_reporttestrunall_proto_depIdxs,
		MessageInfos:      file_reporttestrunall_proto_msgTypes,
	}.Build()
	File_reporttestrunall_proto = out.File
	file_reporttestrunall_proto_rawDesc = nil
	file_reporttestrunall_proto_goTypes = nil
	file_reporttestrunall_proto_depIdxs = nil
}
