// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.27.0
// source: updatetestrun.proto

package updatetestrun

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateTestRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // Add all necessary fields based on the TestRun model
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTestRunRequest) Reset() {
	*x = UpdateTestRunRequest{}
	mi := &file_updatetestrun_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTestRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTestRunRequest) ProtoMessage() {}

func (x *UpdateTestRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_updatetestrun_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTestRunRequest.ProtoReflect.Descriptor instead.
func (*UpdateTestRunRequest) Descriptor() ([]byte, []int) {
	return file_updatetestrun_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateTestRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTestRunRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TestRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TestRun       *TestRun               `protobuf:"bytes,3,opt,name=test_run,json=testRun,proto3" json:"test_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRunResponse) Reset() {
	*x = TestRunResponse{}
	mi := &file_updatetestrun_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRunResponse) ProtoMessage() {}

func (x *TestRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_updatetestrun_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRunResponse.ProtoReflect.Descriptor instead.
func (*TestRunResponse) Descriptor() ([]byte, []int) {
	return file_updatetestrun_proto_rawDescGZIP(), []int{1}
}

func (x *TestRunResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestRunResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestRunResponse) GetTestRun() *TestRun {
	if x != nil {
		return x.TestRun
	}
	return nil
}

type TestRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // Add other fields from TestRun here
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRun) Reset() {
	*x = TestRun{}
	mi := &file_updatetestrun_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRun) ProtoMessage() {}

func (x *TestRun) ProtoReflect() protoreflect.Message {
	mi := &file_updatetestrun_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRun.ProtoReflect.Descriptor instead.
func (*TestRun) Descriptor() ([]byte, []int) {
	return file_updatetestrun_proto_rawDescGZIP(), []int{2}
}

func (x *TestRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestRun) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_updatetestrun_proto protoreflect.FileDescriptor

var file_updatetestrun_proto_rawDesc = []byte{
	0x0a, 0x13, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x74, 0x65, 0x73,
	0x74, 0x72, 0x75, 0x6e, 0x22, 0x3a, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65,
	0x73, 0x74, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x78, 0x0a, 0x0f, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x74, 0x65, 0x73, 0x74, 0x5f,
	0x72, 0x75, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75,
	0x6e, 0x52, 0x07, 0x74, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x22, 0x2d, 0x0a, 0x07, 0x54, 0x65,
	0x73, 0x74, 0x52, 0x75, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x66, 0x0a, 0x0e, 0x54, 0x65, 0x73,
	0x74, 0x52, 0x75, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0d, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x12, 0x23, 0x2e, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75,
	0x6e, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x3b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x74, 0x65,
	0x73, 0x74, 0x72, 0x75, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_updatetestrun_proto_rawDescOnce sync.Once
	file_updatetestrun_proto_rawDescData = file_updatetestrun_proto_rawDesc
)

func file_updatetestrun_proto_rawDescGZIP() []byte {
	file_updatetestrun_proto_rawDescOnce.Do(func() {
		file_updatetestrun_proto_rawDescData = protoimpl.X.CompressGZIP(file_updatetestrun_proto_rawDescData)
	})
	return file_updatetestrun_proto_rawDescData
}

var file_updatetestrun_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_updatetestrun_proto_goTypes = []any{
	(*UpdateTestRunRequest)(nil), // 0: updatetestrun.UpdateTestRunRequest
	(*TestRunResponse)(nil),      // 1: updatetestrun.TestRunResponse
	(*TestRun)(nil),              // 2: updatetestrun.TestRun
}
var file_updatetestrun_proto_depIdxs = []int32{
	2, // 0: updatetestrun.TestRunResponse.test_run:type_name -> updatetestrun.TestRun
	0, // 1: updatetestrun.TestRunService.UpdateTestRun:input_type -> updatetestrun.UpdateTestRunRequest
	1, // 2: updatetestrun.TestRunService.UpdateTestRun:output_type -> updatetestrun.TestRunResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_updatetestrun_proto_init() }
func file_updatetestrun_proto_init() {
	if File_updatetestrun_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_updatetestrun_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_updatetestrun_proto_goTypes,
		DependencyIndexes: file_updatetestrun_proto_depIdxs,
		MessageInfos:      file_updatetestrun_proto_msgTypes,
	}.Build()
	File_updatetestrun_proto = out.File
	file_updatetestrun_proto_rawDesc = nil
	file_updatetestrun_proto_goTypes = nil
	file_updatetestrun_proto_depIdxs = nil
}
