// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0
// source: gettestrunbyid.proto

package gettestrunbyid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTestRunByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTestRunByIDRequest) Reset() {
	*x = GetTestRunByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gettestrunbyid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTestRunByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestRunByIDRequest) ProtoMessage() {}

func (x *GetTestRunByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gettestrunbyid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestRunByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTestRunByIDRequest) Descriptor() ([]byte, []int) {
	return file_gettestrunbyid_proto_rawDescGZIP(), []int{0}
}

func (x *GetTestRunByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TestRun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Add other fields of your TestRun model here
}

func (x *TestRun) Reset() {
	*x = TestRun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gettestrunbyid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRun) ProtoMessage() {}

func (x *TestRun) ProtoReflect() protoreflect.Message {
	mi := &file_gettestrunbyid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRun.ProtoReflect.Descriptor instead.
func (*TestRun) Descriptor() ([]byte, []int) {
	return file_gettestrunbyid_proto_rawDescGZIP(), []int{1}
}

func (x *TestRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTestRunByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TestRun *TestRun `protobuf:"bytes,1,opt,name=test_run,json=testRun,proto3" json:"test_run,omitempty"`
}

func (x *GetTestRunByIDResponse) Reset() {
	*x = GetTestRunByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gettestrunbyid_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTestRunByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestRunByIDResponse) ProtoMessage() {}

func (x *GetTestRunByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gettestrunbyid_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestRunByIDResponse.ProtoReflect.Descriptor instead.
func (*GetTestRunByIDResponse) Descriptor() ([]byte, []int) {
	return file_gettestrunbyid_proto_rawDescGZIP(), []int{2}
}

func (x *GetTestRunByIDResponse) GetTestRun() *TestRun {
	if x != nil {
		return x.TestRun
	}
	return nil
}

var File_gettestrunbyid_proto protoreflect.FileDescriptor

var file_gettestrunbyid_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x65, 0x74, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x62, 0x79, 0x69, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x79, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x42,
	0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x07, 0x54, 0x65,
	0x73, 0x74, 0x52, 0x75, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x54, 0x65, 0x73, 0x74,
	0x52, 0x75, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2d, 0x0a, 0x08, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x75, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x79, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x65,
	0x73, 0x74, 0x52, 0x75, 0x6e, 0x52, 0x07, 0x74, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x32, 0x67,
	0x0a, 0x0e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x55, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x42, 0x79,
	0x49, 0x44, 0x12, 0x20, 0x2e, 0x6d, 0x79, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6d, 0x79, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x3b, 0x67, 0x65,
	0x74, 0x74, 0x65, 0x73, 0x74, 0x72, 0x75, 0x6e, 0x62, 0x79, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gettestrunbyid_proto_rawDescOnce sync.Once
	file_gettestrunbyid_proto_rawDescData = file_gettestrunbyid_proto_rawDesc
)

func file_gettestrunbyid_proto_rawDescGZIP() []byte {
	file_gettestrunbyid_proto_rawDescOnce.Do(func() {
		file_gettestrunbyid_proto_rawDescData = protoimpl.X.CompressGZIP(file_gettestrunbyid_proto_rawDescData)
	})
	return file_gettestrunbyid_proto_rawDescData
}

var file_gettestrunbyid_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gettestrunbyid_proto_goTypes = []interface{}{
	(*GetTestRunByIDRequest)(nil),  // 0: mypackage.GetTestRunByIDRequest
	(*TestRun)(nil),                // 1: mypackage.TestRun
	(*GetTestRunByIDResponse)(nil), // 2: mypackage.GetTestRunByIDResponse
}
var file_gettestrunbyid_proto_depIdxs = []int32{
	1, // 0: mypackage.GetTestRunByIDResponse.test_run:type_name -> mypackage.TestRun
	0, // 1: mypackage.TestRunService.GetTestRunByID:input_type -> mypackage.GetTestRunByIDRequest
	2, // 2: mypackage.TestRunService.GetTestRunByID:output_type -> mypackage.GetTestRunByIDResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gettestrunbyid_proto_init() }
func file_gettestrunbyid_proto_init() {
	if File_gettestrunbyid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gettestrunbyid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTestRunByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gettestrunbyid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestRun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gettestrunbyid_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTestRunByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gettestrunbyid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gettestrunbyid_proto_goTypes,
		DependencyIndexes: file_gettestrunbyid_proto_depIdxs,
		MessageInfos:      file_gettestrunbyid_proto_msgTypes,
	}.Build()
	File_gettestrunbyid_proto = out.File
	file_gettestrunbyid_proto_rawDesc = nil
	file_gettestrunbyid_proto_goTypes = nil
	file_gettestrunbyid_proto_depIdxs = nil
}
