name: golangci-lint
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - uses: evantorrie/mott-the-tidier@v1-beta
        with:
          gomods: |
            **/go.mod
            -tools/go.mod
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-fix go.sum discrepancies
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.54
